<?php
use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;

function drup_siteinfo_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'system_site_information_settings'){
		
	$form['field_siteapikey']['und'][0]['value']['#default_value'] = t( 'TEST' );
	   $form['field_siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API key'),
      '#markup' => t('Add Site API Key'),
    );
	$form['actions']['submit']['#value'] = t('Update Configuration');
	$form['#submit'][] = 'drup_siteinfo_form_submit';
	}
	return $form;
}
function drup_siteinfo_form_submit(&$form, &$form_state)
{ 
  db_insert('siteinfo_apikey')->fields(array('siteapikey' => $form_state->getValue('field_siteapikey'), 'default_value' => 'No API Key yet', ))->execute();
  drupal_set_message("successfully saved Settings"); 
}

?>